CREATE TABLE IF NOT EXISTS users (
user_id INTEGER NOT NULL AUTO_INCREMENT,
username VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
bio VARCHAR(255) DEFAULT '',
num_followers INTEGER DEFAULT 0,
num_following INTEGER DEFAULT 0,
num_posts INTEGER DEFAULT 0,
PRIMARY KEY (user_id))

CREATE TABLE IF NOT EXISTS posts( 
post_id INTEGER NOT NULL AUTO_INCREMENT,
user_id INTEGER NOT NULL,
caption VARCHAR(255),
date DATETIME DEFAULT CURRENT_TIMESTAMP,
num_likes INTEGER DEFAULT 0,
PRIMARY KEY (post_id),
FOREIGN KEY (user_id) REFERENCES users(user_id))

CREATE TABLE IF NOT EXISTS follows( 
follow_id INTEGER NOT NULL AUTO_INCREMENT,
follower_id INTEGER NOT NULL,
followed_id INTEGER NOT NULL,
PRIMARY KEY (follow_id),
FOREIGN KEY (follower_id) REFERENCES users(user_id),
FOREIGN KEY (followed_id) REFERENCES users(user_id))
    
CREATE TABLE IF NOT EXISTS likes( 
like_id INTEGER NOT NULL AUTO_INCREMENT,
post_id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
date DATETIME DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (like_id),
FOREIGN KEY (post_id) REFERENCES posts(post_id),
FOREIGN KEY (user_id) REFERENCES users(user_id))
